version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
      MONGO_INITDB_DATABASE: oz-tech-test
    ports:
      - "27021:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
